### ISSUE TITLE
Add auto send the banned person dm 

### ISSUE THREAD

**Issue by louisplayz-ask** [sylveon/discord-ban-appeals#44]
Plz add auto send the banned person dm that is i approved the unban that it's auto send that person

**Comment by isaacKenyon** [comment]
Bots cannot send DMs to people they dont share servers with

**Comment by sylveon** [comment]
Yeah, once they're banned the bot can't send the user a DM, so this feature can't be implemented

**Comment by louisplayz-ask** [comment]
I have a question for sylveon 

Could you make a staff appeals

**Comment by sylveon** [comment]
A what?

**Comment by louisplayz-ask** [comment]
something like this but then for members to apply for staff 

and also how to i set a status at the bot (watching bans)

**Comment by sylveon** [comment]
There's a branch that shows how you can do that: https://github.com/sylveon/discord-ban-appeals/tree/ms-community-mod-applications

Setting the status of the bot is not doable because we don't keep an active websocket connection. If you want, you can run another bot on the same token and have it show a status.

**Comment by louisplayz-ask** [comment]
okey thx

**Comment by louisplayz-ask** [comment]
if i want to apply for staff on a other account i have this 

![image](https://user-images.githubusercontent.com/96347019/148520338-990c280c-dca1-4d23-86e7-370adc2b85fb.png)

**Comment by jcsumlin** [comment]
you need to set the environment variable`SKIP_BAN_CHECK` to `false` and redeploy

**Comment by louisplayz-ask** [comment]
okey
